### ISSUE TITLE
Configuration in Nextcloud 26 not possible

### ISSUE THREAD

**Issue by KeckIT** [nextcloud/integration_onedrive#36]
While saving, a red exclamation mark persists left to the OneDrive settings.

Log shows warning: 

app":"files_external_onedrive","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead

**Comment by marcelklehr** [comment]
This is not the files_external_onedrive app.
