### ISSUE TITLE
'redirect_uri' is not valid

### ISSUE THREAD

**Issue by simplyknown** [nextcloud/integration_onedrive#46]
Don't know if anyone is still here but I thought I might ask, I have been bashing my head in trying to get this to work, but I can not set the redirect URL, and it causes the error...

'invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.'

The URL in question that I have been given is: http://umbrel.local:8081/apps/integration_onedrive/oauth-redirect . I am using umbrel to run nextcloud so that is why the ip is different. Is there any way to fix this?

**Comment by marcelklehr** [comment]
You cannot use a local domain for this. It needs to be reachable by google.
